name: Go

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/RELEASE'
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize]
    paths:
      - '**/RELEASE'    

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Build
      run: go build -v ./...
      
    - name: Create GitHub Release
      uses: pipe-cd/actions-gh-release@v2.6.0
      with:
        release_file: '**/RELEASE'
        token: ${{ secrets.GITHUB_TOKEN }}

